import {
  NetworkCellIcon,
  BusinessIcon,
  CallIcon,
  CallEndIcon,
  ChatBubbleIcon,
  CommentIcon,
  EmailIcon,
  ForumIcon,
  ImportExportIcon,
  AddCircleIcon,
  AddCircleOutlineIcon,
  AccessTimeIcon,
  NetworkWifiIcon,
  ModeCommentIcon,
  InsertDriveFileIcon,
  CloudOffIcon,
  FileDownloadIcon,
  FileUploadIcon,
  HeadsetIcon,
  KeyboardVoiceIcon,
  LaptopMacIcon,
  MemoryIcon,
  SecurityIcon,
  WatchIcon,
  AudiotrackIcon,
  Brightness3Icon,
  ColorLensIcon,
  EditIcon,
  FlashOnIcon,
  PaletteIcon,
  RemoveRedEyeIcon,
  DirectionsBikeIcon,
  DirectionsBusIcon,
  DirectionsCarIcon,
  DirectionsRailwayIcon,
  DirectionsRunIcon,
  DirectionsSubwayIcon,
  FlightIcon,
  HotelIcon,
  LayersIcon,
  MapIcon,
  MyLocationIcon,
  RestaurantIcon,
  LocalPostOfficeIcon,
  AppsIcon,
  CancelIcon,
  ArrowBackIcon,
  ArrowDownwardIcon,
  ArrowForwardIcon,
  ArrowUpwardIcon,
  RefreshIcon,
  CloseIcon,
  MenuIcon,
  MoreHorizIcon,
  MoreVertIcon,
  EventAvailableIcon,
  EventBusyIcon,
  PowerIcon,
  SmsIcon,
  MmsIcon,
  WifiIcon,
  AcUnitIcon,
  AllInclusiveIcon,
  CasinoIcon,
  FitnessCenterIcon,
  FreeBreakfastIcon,
  SpaIcon,
  CakeIcon,
  GroupIcon,
  GroupAddIcon,
  MoodIcon,
  MoodBadIcon,
  PersonIcon,
  PersonAddIcon,
  SentimentVeryDissatisfiedIcon,
  SentimentDissatisfiedIcon,
  SentimentNeutralIcon,
  SentimentSatisfiedIcon,
  SentimentVerySatisfiedIcon,
  ShareIcon,
  WhatshotIcon,
  StarIcon,
} from '../../src/icons';

export const iconList = [
  <NetworkCellIcon fill={'skyblue'} size={40} />,
  <BusinessIcon fill={'skyblue'} size={40} />,
  <CallIcon fill={'skyblue'} size={40} />,
  <CallEndIcon fill={'skyblue'} size={40} />,
  <ChatBubbleIcon fill={'skyblue'} size={40} />,
  <CommentIcon fill={'skyblue'} size={40} />,
  <EmailIcon fill={'skyblue'} size={40} />,
  <ForumIcon fill={'skyblue'} size={40} />,
  <ImportExportIcon fill={'skyblue'} size={40} />,
  <AddCircleIcon fill={'skyblue'} size={40} />,
  <AddCircleOutlineIcon fill={'skyblue'} size={40} />,
  <AccessTimeIcon fill={'skyblue'} size={40} />,
  <NetworkWifiIcon fill={'skyblue'} size={40} />,
  <ModeCommentIcon fill={'skyblue'} size={40} />,
  <InsertDriveFileIcon fill={'skyblue'} size={40} />,
  <CloudOffIcon fill={'skyblue'} size={40} />,
  <FileDownloadIcon fill={'skyblue'} size={40} />,
  <FileUploadIcon fill={'skyblue'} size={40} />,
  <HeadsetIcon fill={'skyblue'} size={40} />,
  <KeyboardVoiceIcon fill={'skyblue'} size={40} />,
  <LaptopMacIcon fill={'skyblue'} size={40} />,
  <MemoryIcon fill={'skyblue'} size={40} />,
  <SecurityIcon fill={'skyblue'} size={40} />,
  <WatchIcon fill={'skyblue'} size={40} />,
  <AudiotrackIcon fill={'skyblue'} size={40} />,
  <Brightness3Icon fill={'skyblue'} size={40} />,
  <ColorLensIcon fill={'skyblue'} size={40} />,
  <EditIcon fill={'skyblue'} size={40} />,
  <FlashOnIcon fill={'skyblue'} size={40} />,
  <PaletteIcon fill={'skyblue'} size={40} />,
  <RemoveRedEyeIcon fill={'skyblue'} size={40} />,
  <DirectionsBikeIcon fill={'skyblue'} size={40} />,
  <DirectionsBusIcon fill={'skyblue'} size={40} />,
  <DirectionsCarIcon fill={'skyblue'} size={40} />,
  <DirectionsRailwayIcon fill={'skyblue'} size={40} />,
  <DirectionsRunIcon fill={'skyblue'} size={40} />,
  <DirectionsSubwayIcon fill={'skyblue'} size={40} />,
  <FlightIcon fill={'skyblue'} size={40} />,
  <HotelIcon fill={'skyblue'} size={40} />,
  <LayersIcon fill={'skyblue'} size={40} />,
  <MapIcon fill={'skyblue'} size={40} />,
  <MyLocationIcon fill={'skyblue'} size={40} />,
  <RestaurantIcon fill={'skyblue'} size={40} />,
  <LocalPostOfficeIcon fill={'skyblue'} size={40} />,
  <AppsIcon fill={'skyblue'} size={40} />,
  <CancelIcon fill={'skyblue'} size={40} />,
  <ArrowBackIcon fill={'skyblue'} size={40} />,
  <ArrowDownwardIcon fill={'skyblue'} size={40} />,
  <ArrowForwardIcon fill={'skyblue'} size={40} />,
  <ArrowUpwardIcon fill={'skyblue'} size={40} />,
  <RefreshIcon fill={'skyblue'} size={40} />,
  <CloseIcon fill={'skyblue'} size={40} />,
  <MenuIcon fill={'skyblue'} size={40} />,
  <MoreHorizIcon fill={'skyblue'} size={40} />,
  <MoreVertIcon fill={'skyblue'} size={40} />,
  <EventAvailableIcon fill={'skyblue'} size={40} />,
  <EventBusyIcon fill={'skyblue'} size={40} />,
  <PowerIcon fill={'skyblue'} size={40} />,
  <SmsIcon fill={'skyblue'} size={40} />,
  <MmsIcon fill={'skyblue'} size={40} />,
  <WifiIcon fill={'skyblue'} size={40} />,
  <AcUnitIcon fill={'skyblue'} size={40} />,
  <AllInclusiveIcon fill={'skyblue'} size={40} />,
  <CasinoIcon fill={'skyblue'} size={40} />,
  <FitnessCenterIcon fill={'skyblue'} size={40} />,
  <FreeBreakfastIcon fill={'skyblue'} size={40} />,
  <SpaIcon fill={'skyblue'} size={40} />,
  <CakeIcon fill={'skyblue'} size={40} />,
  <GroupIcon fill={'skyblue'} size={40} />,
  <GroupAddIcon fill={'skyblue'} size={40} />,
  <MoodIcon fill={'skyblue'} size={40} />,
  <MoodBadIcon fill={'skyblue'} size={40} />,
  <PersonIcon fill={'skyblue'} size={40} />,
  <PersonAddIcon fill={'skyblue'} size={40} />,
  <SentimentVeryDissatisfiedIcon fill={'skyblue'} size={40} />,
  <SentimentDissatisfiedIcon fill={'skyblue'} size={40} />,
  <SentimentNeutralIcon fill={'skyblue'} size={40} />,
  <SentimentSatisfiedIcon fill={'skyblue'} size={40} />,
  <SentimentVerySatisfiedIcon fill={'skyblue'} size={40} />,
  <ShareIcon fill={'skyblue'} size={40} />,
  <WhatshotIcon fill={'skyblue'} size={40} />,
  <StarIcon fill={'skyblue'} size={40} />,
];
