// @flow

import {
  NetworkCellIcon,
  BusinessIcon,
  CallIcon,
  CallEndIcon,
  ChatBubbleIcon,
  CommentIcon,
  EmailIcon,
  ForumIcon,
  ImportExportIcon,
  AddCircleIcon,
  AddCircleOutlineIcon,
  AccessTimeIcon,
  NetworkWifiIcon,
  ModeCommentIcon,
  InsertDriveFileIcon,
  CloudOffIcon,
  FileDownloadIcon,
  FileUploadIcon,
  HeadsetIcon,
  KeyboardVoiceIcon,
  LaptopMacIcon,
  MemoryIcon,
  SecurityIcon,
  WatchIcon,
  AudiotrackIcon,
  Brightness3Icon,
  ColorLensIcon,
  EditIcon,
  FlashOnIcon,
  PaletteIcon,
  RemoveRedEyeIcon,
  DirectionsBikeIcon,
  DirectionsBusIcon,
  DirectionsCarIcon,
  DirectionsRailwayIcon,
  DirectionsRunIcon,
  DirectionsSubwayIcon,
  FlightIcon,
  HotelIcon,
  LayersIcon,
  MapIcon,
  MyLocationIcon,
  RestaurantIcon,
  LocalPostOfficeIcon,
  AppsIcon,
  CancelIcon,
  ArrowBackIcon,
  ArrowDownwardIcon,
  ArrowForwardIcon,
  ArrowUpwardIcon,
  RefreshIcon,
  CloseIcon,
  MenuIcon,
  MoreHorizIcon,
  MoreVertIcon,
  EventAvailableIcon,
  EventBusyIcon,
  PowerIcon,
  SmsIcon,
  MmsIcon,
  WifiIcon,
  AcUnitIcon,
  AllInclusiveIcon,
  CasinoIcon,
  FitnessCenterIcon,
  FreeBreakfastIcon,
  SpaIcon,
  CakeIcon,
  GroupIcon,
  GroupAddIcon,
  MoodIcon,
  MoodBadIcon,
  PersonIcon,
  PersonAddIcon,
  SentimentVeryDissatisfiedIcon,
  SentimentDissatisfiedIcon,
  SentimentNeutralIcon,
  SentimentSatisfiedIcon,
  SentimentVerySatisfiedIcon,
  ShareIcon,
  WhatshotIcon,
  StarIcon
} from "../../src/icons";

export const iconList = [
  NetworkCellIcon,
  BusinessIcon,
  CallIcon,
  CallEndIcon,
  ChatBubbleIcon,
  CommentIcon,
  EmailIcon,
  ForumIcon,
  ImportExportIcon,
  AddCircleIcon,
  AddCircleOutlineIcon,
  AccessTimeIcon,
  NetworkWifiIcon,
  ModeCommentIcon,
  InsertDriveFileIcon,
  CloudOffIcon,
  FileDownloadIcon,
  FileUploadIcon,
  HeadsetIcon,
  KeyboardVoiceIcon,
  LaptopMacIcon,
  MemoryIcon,
  SecurityIcon,
  WatchIcon,
  AudiotrackIcon,
  Brightness3Icon,
  ColorLensIcon,
  EditIcon,
  FlashOnIcon,
  PaletteIcon,
  RemoveRedEyeIcon,
  DirectionsBikeIcon,
  DirectionsBusIcon,
  DirectionsCarIcon,
  DirectionsRailwayIcon,
  DirectionsRunIcon,
  DirectionsSubwayIcon,
  FlightIcon,
  HotelIcon,
  LayersIcon,
  MapIcon,
  MyLocationIcon,
  RestaurantIcon,
  LocalPostOfficeIcon,
  AppsIcon,
  CancelIcon,
  ArrowBackIcon,
  ArrowDownwardIcon,
  ArrowForwardIcon,
  ArrowUpwardIcon,
  RefreshIcon,
  CloseIcon,
  MenuIcon,
  MoreHorizIcon,
  MoreVertIcon,
  EventAvailableIcon,
  EventBusyIcon,
  PowerIcon,
  SmsIcon,
  MmsIcon,
  WifiIcon,
  AcUnitIcon,
  AllInclusiveIcon,
  CasinoIcon,
  FitnessCenterIcon,
  FreeBreakfastIcon,
  SpaIcon,
  CakeIcon,
  GroupIcon,
  GroupAddIcon,
  MoodIcon,
  MoodBadIcon,
  PersonIcon,
  PersonAddIcon,
  SentimentVeryDissatisfiedIcon,
  SentimentDissatisfiedIcon,
  SentimentNeutralIcon,
  SentimentSatisfiedIcon,
  SentimentVerySatisfiedIcon,
  ShareIcon,
  WhatshotIcon,
  StarIcon
];

// export const iconList: Array<Object> = [
//   <NetworkCellIcon key="networkCellIcon" fill={"skyblue"} size={40} />,
//   <BusinessIcon key="businessIcon" fill={"skyblue"} size={40} />,
//   <CallIcon key="callIcons" fill={"skyblue"} size={40} />,
//   <CallEndIcon key="callEndIcon" fill={"skyblue"} size={40} />,
//   <ChatBubbleIcon key="chatBubbleIcon" fill={"skyblue"} size={40} />,
//   <CommentIcon key="commentIcon" fill={"skyblue"} size={40} />,
//   <EmailIcon key="emailIcon" fill={"skyblue"} size={40} />,
//   <ForumIcon key="forumIcon" fill={"skyblue"} size={40} />,
//   <ImportExportIcon key="importExportIcon" fill={"skyblue"} size={40} />,
//   <AddCircleIcon key="addCircleIcon" fill={"skyblue"} size={40} />,
//   <AddCircleOutlineIcon key="addCircleOutlineIcon" fill={"skyblue"} size={40} />,
//   <AccessTimeIcon key="accessTimeIcon" fill={"skyblue"} size={40} />,
//   <NetworkWifiIcon key="networkWifiIcon" fill={"skyblue"} size={40} />,
//   <ModeCommentIcon key="modeCommentIcon" fill={"skyblue"} size={40} />,
//   <InsertDriveFileIcon key="insertDriveFileIcon" fill={"skyblue"} size={40} />,
//   <CloudOffIcon key="cloudOffIcon" fill={"skyblue"} size={40} />,
//   <FileDownloadIcon key="fileDownloadIcon" fill={"skyblue"} size={40} />,
//   <FileUploadIcon key="fileUploadIcon" fill={"skyblue"} size={40} />,
//   <HeadsetIcon key="headsetIcon" fill={"skyblue"} size={40} />,
//   <KeyboardVoiceIcon key="keyboardVoiceIcon" fill={"skyblue"} size={40} />,
//   <LaptopMacIcon key="laptopMacIcon" fill={"skyblue"} size={40} />,
//   <MemoryIcon key="memoryIcon" fill={"skyblue"} size={40} />,
//   <SecurityIcon key="securityIcon" fill={"skyblue"} size={40} />,
//   <WatchIcon key="watchIcon" fill={"skyblue"} size={40} />,
//   <AudiotrackIcon key="audiotrackIcon" fill={"skyblue"} size={40} />,
//   <Brightness3Icon key="brightness3Icon" fill={"skyblue"} size={40} />,
//   <ColorLensIcon key="colorLensIcon" fill={"skyblue"} size={40} />,
//   <EditIcon key="editIcon" fill={"skyblue"} size={40} />,
//   <FlashOnIcon fill={"skyblue"} size={40} />,
//   <PaletteIcon fill={"skyblue"} size={40} />,
//   <RemoveRedEyeIcon fill={"skyblue"} size={40} />,
//   <DirectionsBikeIcon fill={"skyblue"} size={40} />,
//   <DirectionsBusIcon fill={"skyblue"} size={40} />,
//   <DirectionsCarIcon fill={"skyblue"} size={40} />,
//   <DirectionsRailwayIcon fill={"skyblue"} size={40} />,
//   <DirectionsRunIcon fill={"skyblue"} size={40} />,
//   <DirectionsSubwayIcon fill={"skyblue"} size={40} />,
//   <FlightIcon fill={"skyblue"} size={40} />,
//   <HotelIcon fill={"skyblue"} size={40} />,
//   <LayersIcon fill={"skyblue"} size={40} />,
//   <MapIcon fill={"skyblue"} size={40} />,
//   <MyLocationIcon fill={"skyblue"} size={40} />,
//   <RestaurantIcon fill={"skyblue"} size={40} />,
//   <LocalPostOfficeIcon fill={"skyblue"} size={40} />,
//   <AppsIcon fill={"skyblue"} size={40} />,
//   <CancelIcon fill={"skyblue"} size={40} />,
//   <ArrowBackIcon fill={"skyblue"} size={40} />,
//   <ArrowDownwardIcon fill={"skyblue"} size={40} />,
//   <ArrowForwardIcon fill={"skyblue"} size={40} />,
//   <ArrowUpwardIcon fill={"skyblue"} size={40} />,
//   <RefreshIcon fill={"skyblue"} size={40} />,
//   <CloseIcon fill={"skyblue"} size={40} />,
//   <MenuIcon fill={"skyblue"} size={40} />,
//   <MoreHorizIcon fill={"skyblue"} size={40} />,
//   <MoreVertIcon fill={"skyblue"} size={40} />,
//   <EventAvailableIcon fill={"skyblue"} size={40} />,
//   <EventBusyIcon fill={"skyblue"} size={40} />,
//   <PowerIcon fill={"skyblue"} size={40} />,
//   <SmsIcon fill={"skyblue"} size={40} />,
//   <MmsIcon fill={"skyblue"} size={40} />,
//   <WifiIcon fill={"skyblue"} size={40} />,
//   <AcUnitIcon fill={"skyblue"} size={40} />,
//   <AllInclusiveIcon fill={"skyblue"} size={40} />,
//   <CasinoIcon fill={"skyblue"} size={40} />,
//   <FitnessCenterIcon fill={"skyblue"} size={40} />,
//   <FreeBreakfastIcon fill={"skyblue"} size={40} />,
//   <SpaIcon fill={"skyblue"} size={40} />,
//   <CakeIcon fill={"skyblue"} size={40} />,
//   <GroupIcon fill={"skyblue"} size={40} />,
//   <GroupAddIcon fill={"skyblue"} size={40} />,
//   <MoodIcon fill={"skyblue"} size={40} />,
//   <MoodBadIcon fill={"skyblue"} size={40} />,
//   <PersonIcon fill={"skyblue"} size={40} />,
//   <PersonAddIcon fill={"skyblue"} size={40} />,
//   <SentimentVeryDissatisfiedIcon fill={"skyblue"} size={40} />,
//   <SentimentDissatisfiedIcon fill={"skyblue"} size={40} />,
//   <SentimentNeutralIcon fill={"skyblue"} size={40} />,
//   <SentimentSatisfiedIcon fill={"skyblue"} size={40} />,
//   <SentimentVerySatisfiedIcon fill={"skyblue"} size={40} />,
//   <ShareIcon fill={"skyblue"} size={40} />,
//   <WhatshotIcon fill={"skyblue"} size={40} />,
//   <StarIcon fill={"skyblue"} size={40} />
// ];
